name = "CVar"
decl = "struct CVar clearScope"
doc = """
A **C**onsole **Var**iable, either defined in [CVARINFO] or by the engine.

All Get and Set operations will work regardless of the real type of
the CVar, as [they are not "strongly" typed.][cvar conversions]
"""

[class-methods.ungrouped.FindCVar]
decl = "static CVar {FindCVar}(name n)"
doc = """
Returns a server CVar by name, or `null` if none is found.
"""

[class-methods.ungrouped.GetCVar]
decl = "static CVar {GetCVar}(name n, [PlayerInfo] player = null)"
doc = """
Returns a user or server CVar by name, with `player` as the user if
applicable, or `null` if none is found.
"""

[[instance-methods.groups.Getters]]
decl = [
	"bool {GetBool}()",
	"double {GetFloat}()",
	"int {GetInt}()",
	"string {GetString}()",
]
doc = """
Returns a representation of the value of the CVar.
"""

[[instance-methods.groups.Getters]]
decl = "[ECVarType] {GetRealType}()"
doc = """
Returns the type of the CVar as it was defined.
"""

[[instance-methods.groups.Setters]]
decl = [
	"void {SetBool}(bool v)",
	"void {SetFloat}(double v)",
	"void {SetInt}(int v)",
	"void {SetString}(string v)",
]
doc = """
Sets the CVar to `v`.
"""

[[instance-methods.groups.Setters]]
decl = "int {ResetToDefault}()"
doc = """
Resets the CVar to its default value and returns 0. The purpose of the
return is unknown.
"""
